import assert from 'node:assert/strict';
import {creatureDefaultKey,readCreatureDefault,saveCreatureDefault} from '../src/creature-defaults';
import {creatureDraftKey,readCreatureDraft} from '../src/creature-categories';
import {presetCreature} from '../src/creature-schema';
const values=new Map<string,string>(),storage={getItem:(key:string)=>values.get(key)??null,setItem:(key:string,value:string)=>{values.set(key,value);}};
assert.deepEqual(readCreatureDefault(storage,'skeleton'),presetCreature('skeleton'));
const skeleton=presetCreature('skeleton');skeleton.anatomy.arms=1.23;skeleton.appearance.primary='#abcdef';skeleton.behavior.speed=3.7;
saveCreatureDefault(storage,skeleton);
assert.deepEqual(readCreatureDefault(storage,'skeleton'),skeleton);
assert.deepEqual(readCreatureDefault(storage,'werewolf'),presetCreature('werewolf'));
skeleton.anatomy.arms=.8;saveCreatureDefault(storage,skeleton);
assert.equal(readCreatureDefault(storage,'skeleton').anatomy.arms,.8);
const draft=presetCreature('skeleton');draft.anatomy.arms=1.3;
storage.setItem(creatureDraftKey('normal'),JSON.stringify(draft));
assert.equal(readCreatureDraft(storage,'normal').anatomy.arms,.8,'Saved default must load on reopen');
const sdf=presetCreature('wolfSdf');sdf.body.bulk=.8;saveCreatureDefault(storage,sdf);
assert.deepEqual(readCreatureDraft(storage,'sdf'),sdf);
storage.setItem(creatureDefaultKey('skeleton'),JSON.stringify(sdf));
assert.equal(readCreatureDefault(storage,'skeleton').species,'skeleton');
storage.setItem(creatureDefaultKey('skeleton'),'broken');assert.deepEqual(readCreatureDefault(storage,'skeleton'),presetCreature('skeleton'));
assert.throws(()=>saveCreatureDefault({getItem:storage.getItem,setItem(){throw Error('Storage full');}},skeleton),/Storage full/);
console.log('Independent creature defaults, overwrite, reopen, SDF separation, corrupt data and storage failures passed.');
