import assert from 'node:assert/strict';
import {creatureCategory,creatureDraftKey,readCreatureDraft} from '../src/creature-categories';
import {CREATURE_SPECIES,presetCreature} from '../src/creature-schema';
const values=new Map<string,string>(),storage={getItem:(key:string)=>values.get(key)??null};
const sdf=['wolfSdf','wolfLowpolySdf','boar','werewolfSdf','ratSdf','tarantulaSdf'];
for(const species of Object.keys(CREATURE_SPECIES) as Array<keyof typeof CREATURE_SPECIES>)assert.equal(creatureCategory(species),sdf.includes(species)?'sdf':'normal');
assert.notEqual(creatureDraftKey('normal'),creatureDraftKey('sdf'));
const old=presetCreature('wolfLowpolySdf');old.name='Meu lobo';old.anatomy.ears=1.2;
values.set('abrigo-creature-v1',JSON.stringify(old));
assert.deepEqual(readCreatureDraft(storage,'sdf'),old);
assert.equal(readCreatureDraft(storage,'normal').species,'wolf');
const normal=presetCreature('rat');normal.name='Meu rato';
values.set(creatureDraftKey('normal'),JSON.stringify(normal));
assert.deepEqual(readCreatureDraft(storage,'normal'),normal);
assert.deepEqual(readCreatureDraft(storage,'sdf'),old);
const updated=presetCreature('boar');updated.name='Meu javali';
values.set(creatureDraftKey('sdf'),JSON.stringify(updated));
assert.deepEqual(readCreatureDraft(storage,'sdf'),updated);
assert.deepEqual(readCreatureDraft(storage,'normal'),normal);
values.set(creatureDraftKey('sdf'),'invalid');
assert.deepEqual(readCreatureDraft(storage,'sdf'),old);
assert.equal(values.get('abrigo-creature-v1'),JSON.stringify(old),'migration must preserve legacy storage');
console.log('Creature categories: canonical SDF roster, separate drafts, legacy migration, saved override and invalid-draft fallback passed.');
