import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import {createHash} from 'node:crypto';
import * as THREE from 'three';
import {createCreature} from '../src/creature';
import {presetCreature,randomCreature,validateCreatureSpec} from '../src/creature-schema';
import {buildWolfSdfData,wolfSdfSeed,WOLF_SDF_ATTACK_DURATION,WOLF_SDF_ATTACK_IMPACT} from '../src/wolf-sdf-detail';
import {buildSync} from '../vendor/threejs-procedural-animals/src/core/build/pipeline.js';
import wolf from '../vendor/threejs-procedural-animals/src/species/wolf/index.js';
import {FAUNA_PROCEDURAL_SDF,getCreatureBuild} from '../src/creature-builds';
const reference=presetCreature('wolfSdf');
assert.deepEqual(reference.behavior,presetCreature('wolf').behavior,'new wolf keeps the original gameplay defaults');
assert.equal(presetCreature('wolf').name,'Lobo da mata');
const manifest=JSON.parse(readFileSync('docs/boar-vendor-lock.json','utf8'));
assert.deepEqual(reference.generator,FAUNA_PROCEDURAL_SDF);
const legacy=structuredClone(reference);delete legacy.generator;
assert.deepEqual(validateCreatureSpec(legacy).generator,FAUNA_PROCEDURAL_SDF);
assert.deepEqual(validateCreatureSpec({...reference,generator:{id:'fake',sourceCommit:'fake'}}).generator,FAUNA_PROCEDURAL_SDF);
assert.equal(validateCreatureSpec({...presetCreature('wolf'),generator:FAUNA_PROCEDURAL_SDF}).generator,undefined);
assert.equal(getCreatureBuild('wolf'),undefined);
assert.equal(getCreatureBuild('wolfSdf'),FAUNA_PROCEDURAL_SDF);
assert.equal(FAUNA_PROCEDURAL_SDF.sourceVersion,JSON.parse(readFileSync('vendor/threejs-procedural-animals/package.json','utf8')).version);
assert.equal(FAUNA_PROCEDURAL_SDF.sourceCommit,manifest.commit);
assert.deepEqual(randomCreature('same','wolfSdf').generator,FAUNA_PROCEDURAL_SDF);
(reference.generator as any).name='Changed';
assert.equal(presetCreature('wolfSdf').generator!.name,FAUNA_PROCEDURAL_SDF.name,'recipe mutated global provenance');
reference.generator={...FAUNA_PROCEDURAL_SDF};
for(const file of manifest.files){const bytes=readFileSync('vendor/threejs-procedural-animals/'+file.path);assert.equal(bytes.length,file.bytes);assert.equal(createHash('sha256').update(bytes).digest('hex'),file.sha256,file.path);}
assert.equal(wolfSdfSeed('same'),wolfSdfSeed('same'));assert.notEqual(wolfSdfSeed('same'),wolfSdfSeed('other'));
assert.deepEqual(validateCreatureSpec(JSON.parse(JSON.stringify(reference))),reference);
assert.deepEqual(randomCreature('same','wolfSdf'),randomCreature('same','wolfSdf'));
// At neutral controls, exactly the upstream SDF surface/rig, not a reconstruction.
const original=buildSync(wolf,{seed:wolfSdfSeed(reference.seed),quality:'low',variant:'grey',sex:'male'});
const integrated=buildWolfSdfData(reference,'low');
for(const key of ['pos','nrm','index','skinIndex','skinWeight','tint','coat'])assert.deepEqual(integrated[key],original[key],key+' changed');
assert.deepEqual(integrated.bones,original.bones);assert.deepEqual(integrated.joints,original.joints);
const model=createCreature(reference,{detail:'low'});model.root.position.set(2,3,4);model.root.rotation.y=.7;
assert.deepEqual(model.root.userData.generator,FAUNA_PROCEDURAL_SDF);
assert.equal(model.root.userData.rig.species,'wolfSdf');
const legacyModel=createCreature(presetCreature('wolf'),{detail:'high'});assert.equal(legacyModel.root.userData.generator,undefined);assert(legacyModel.nodes.frontLKnee);legacyModel.dispose();
const worldPosition=model.root.position.clone(),worldRotation=model.root.quaternion.clone();
model.update(0,'idle');const resting=model.nodes.head.getWorldPosition(new THREE.Vector3());
model.update(0,'attack');model.update(WOLF_SDF_ATTACK_IMPACT,'attack');const strike=model.nodes.head.getWorldPosition(new THREE.Vector3());assert(resting.distanceTo(strike)>.01,'bite-lunge must move head');
model.update(WOLF_SDF_ATTACK_DURATION+1,'attack');const recovered=model.nodes.head.getWorldPosition(new THREE.Vector3());assert(strike.distanceTo(recovered)>.01,'bite-lunge must recover');
assert(model.root.position.equals(worldPosition));assert(model.root.quaternion.equals(worldRotation));
for(const motion of ['idle','move','run','attack'] as const)for(const t of [0,.17,.7,1.8,20]){model.update(t,motion);model.root.updateMatrixWorld(true);const box=new THREE.Box3().setFromObject(model.root);assert(box.min.y>worldPosition.y-.07,'boar penetrates ground');assert(box.getSize(new THREE.Vector3()).length()<4,'virtual locomotion leaks into world bounds');assert(box.getCenter(new THREE.Vector3()).distanceTo(worldPosition)<2,'boar drifts away from host');}
const tintBefore=Array.from(integrated.tint),modified=structuredClone(reference);modified.appearance.primary='#81432a';
const colored=createCreature(modified,{detail:'low'});assert.deepEqual(Array.from(integrated.tint),tintBefore,'colour edit mutates cached individual');colored.dispose();
const fallback=createCreature(reference,{detail:'low',instancing:false});fallback.update(0,'move');const mesh=fallback.root.getObjectByName('base') as THREE.Mesh;
const p=Array.from(mesh.geometry.attributes.position.array);fallback.update(.3,'move');assert.notDeepEqual(Array.from(mesh.geometry.attributes.position.array),p,'SVG body must animate');
assert.deepEqual(integrated.nrm,original.nrm,'SVG normal updates mutate cached geometry');
fallback.root.traverse(o=>{assert(o.matrixWorld.elements.every(Number.isFinite));});fallback.dispose();fallback.dispose();model.dispose();model.dispose();
console.log('Wolf SDF: source hashes, exact neutral upstream surface/rig, seed recipes, single bite-lunge/recovery, host root, isolated colour cache and animated SVG fallback passed.');
