import assert from 'node:assert/strict';
import {presetCharacter} from '../src/schema';
import {loadZombiePresets,saveZombiePreset,ZOMBIE_PRESETS_STORE} from '../src/zombie-presets';
const data=new Map<string,string>(),storage={getItem:(k:string)=>data.get(k)??null,setItem:(k:string,v:string)=>{data.set(k,v);}};
assert.deepEqual(loadZombiePresets(storage),[]);
const zombie=presetCharacter('zumbi');zombie.items.object='invisible';zombie.items.placement='right';
const first=saveZombiePreset(storage,zombie,'Zumbi da mata');
zombie.body.height=1.6;zombie.outfit.topColor='#302922';
const second=saveZombiePreset(storage,zombie,'Zumbi pequeno');
assert.notEqual(first.id,second.id);assert.equal(loadZombiePresets(storage).length,2);
assert.deepEqual(loadZombiePresets(storage)[0].spec,first.spec);
const reloaded=loadZombiePresets(storage);reloaded[0].spec.name='Mutação externa';assert.notEqual(loadZombiePresets(storage)[0].spec.name,'Mutação externa');
saveZombiePreset(storage,zombie,'Zumbi da mata',first.id);
assert.deepEqual(loadZombiePresets(storage)[0].spec,zombie);assert.equal(loadZombiePresets(storage).length,2);
assert.throws(()=>saveZombiePreset(storage,zombie,'zumbi DA MATA'));
assert.throws(()=>saveZombiePreset(storage,presetCharacter('lenhador'),'Humano'));
assert.throws(()=>saveZombiePreset(storage,zombie,''));
assert.throws(()=>saveZombiePreset(storage,zombie,'Novo','zombie-missing'));
const preserved=data.get(ZOMBIE_PRESETS_STORE);assert.throws(()=>saveZombiePreset({...storage,setItem:()=>{throw Error('Quota');}},zombie,'Falha'));
assert.equal(data.get(ZOMBIE_PRESETS_STORE),preserved);
data.set(ZOMBIE_PRESETS_STORE,'{broken');assert.throws(()=>loadZombiePresets(storage));assert.throws(()=>saveZombiePreset(storage,zombie,'Não apagar'));assert.equal(data.get(ZOMBIE_PRESETS_STORE),'{broken');
console.log('Zombie presets: reload, independent full recipes, explicit overwrite, copies, duplicate names, category validation, quota and corruption preservation passed.');
