import {createPreview} from './scene';
import {prepareFauna} from './fauna-prepare';
import {getCreatureBuild} from './creature-builds';
import {creatureCategory,creatureDraftKey,readCreatureDraft,type CreatureCategory} from './creature-categories';
import {clone} from './schema';
import {icon} from './icons';
import {CREATURE_SPECIES,CREATURE_FIELDS,presetCreature,randomCreature,validateCreatureSpec,type CreatureSpec,type CreatureSpecies,type CreatureMotion} from './creature-schema';

const esc=(s:unknown)=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]!));
const ratControls={headSize:'Tamanho da cabeça',muzzleLength:'Comprimento do focinho',pawSize:'Tamanho dos pés',whiskerLength:'Comprimento dos bigodes'};
const spiderControls={abdomenWidth:'Largura do abdômen',abdomenHeight:'Altura do abdômen',abdomenLength:'Comprimento do abdômen',headWidth:'Largura da cabeça',headHeight:'Altura da cabeça',headLength:'Comprimento da cabeça',bodyHeight:'Altura do corpo',eyeSize:'Tamanho dos olhos'};
const scorpionControls={bodyWidth:'Largura da carapaça',bodyLength:'Comprimento do corpo',bodyHeight:'Altura do corpo',clawSize:'Tamanho das pinças',clawReach:'Alcance das pinças',clawOpening:'Abertura das pinças',tailThickness:'Espessura da cauda',stingerSize:'Tamanho do ferrão'};
const descriptions={wolfLowpolySdf:'Mesmo lobo SDF · malha simplificada',wolfSdf:'Predador territorial · pelagem SDF',boar:'Presas e pelagem · quadrúpede procedural',ratSdf:'Roedor · pelagem SDF e bigodes articulados',rat:'Roedor · patas, bigodes e cauda articulados',skeleton:'Ossos articulados · esqueleto procedural',scorpion:'Oito patas · pinças e cauda articuladas',tarantulaSdf:'Oito patas · pelos SDF e presas articuladas',spider:'Oito patas articuladas · aranha procedural',wolf:'Predador territorial · quadrúpede',werewolfSdf:'Predador bípede · escultura e pelagem SDF',werewolf:'Predador bípede · garras e presas',bat:'Ameaça aérea · voo articulado',swarm:'Vespas · movimento coletivo',snake:'Emboscada rasteira · corpo contínuo'};
const motions={wolfLowpolySdf:['Em alerta','Caminhar','Morder'],wolfSdf:['Em alerta','Caminhar','Morder'],boar:['Em alerta','Caminhar','Investida'],ratSdf:['Repouso','Caminhar','Morder'],rat:['Repouso','Caminhar','Morder'],skeleton:['Repouso','Caminhar','Golpear'],scorpion:['Repouso','Caminhar','Atacar'],tarantulaSdf:['Repouso','Caminhar','Atacar'],spider:['Repouso','Caminhar','Atacar'],wolf:['Em alerta','Caminhar','Morder'],werewolfSdf:['Em alerta','Caminhar','Golpear'],werewolf:['Em alerta','Caminhar','Golpear'],bat:['Pairar','Voar','Investida'],swarm:['Circular','Deslocar','Atacar'],snake:['Repouso','Rastejar','Bote']};
const speciesIcon=(id:string)=>`<svg viewBox="0 0 32 32" width="30" height="30" fill="none" stroke="currentColor" stroke-width="1.6" stroke-linejoin="round" aria-hidden="true"><path d="${{wolfLowpolySdf:'M5 4 13 9 19 9 27 4 25 20 16 28 7 20Z M10 16 13 17 M19 17 22 16 M13 22 19 22 16 25Z',wolfSdf:'M5 4 13 9 19 9 27 4 25 20 16 28 7 20Z M10 16 13 17 M19 17 22 16 M13 22 19 22 16 25Z',boar:'M3 17 7 10 20 10 26 15 30 15 30 21 25 22 22 27 M9 22 9 27 M7 10 9 5 14 10 M25 20 24 25 29 22',ratSdf:'M5 23C1 23 1 15 6 15 M6 22C6 10 20 10 25 18L29 20 24 23Z M17 13C12 3 23 3 22 15 M24 18 25 18 M10 23 9 27 M21 23 22 27',rat:'M5 23C1 23 1 15 6 15 M6 22C6 10 20 10 25 18L29 20 24 23Z M17 13C12 3 23 3 22 15 M24 18 25 18 M10 23 9 27 M21 23 22 27',skeleton:'M10 3 22 3 24 10 20 15 12 15 8 10Z M12 8 14 8 M18 8 20 8 M14 12 18 12 M16 15 16 25 M9 18 23 18 M10 21 22 21 M6 16 4 27 M26 16 28 27 M12 25 10 31 M20 25 22 31',scorpion:'M12 14 20 14 21 22 11 22Z M16 14 16 8 22 4 25 7 21 10 M11 16 6 12 3 8 1 12 5 15 M21 16 26 12 29 8 31 12 27 15 M11 18 5 20 2 24 M11 21 7 26 M21 18 27 20 30 24 M21 21 25 26',tarantulaSdf:'M12 12C12 7 20 7 20 12L20 19C20 25 12 25 12 19Z M12 13 7 7 3 5 M12 15 6 12 2 14 M12 18 6 20 2 24 M13 21 9 26 8 30 M20 13 25 7 29 5 M20 15 26 12 30 14 M20 18 26 20 30 24 M19 21 23 26 24 30',spider:'M12 12C12 7 20 7 20 12L20 19C20 25 12 25 12 19Z M12 13 7 7 3 5 M12 15 6 12 2 14 M12 18 6 20 2 24 M13 21 9 26 8 30 M20 13 25 7 29 5 M20 15 26 12 30 14 M20 18 26 20 30 24 M19 21 23 26 24 30',werewolfSdf:'M8 3 13 8 19 8 24 3 23 16 16 21 9 16Z M12 12 14 13 M18 13 20 12 M13 17 19 17 M9 20 4 25 6 30 M23 20 28 25 26 30 M11 22 21 22 20 30 12 30Z',werewolf:'M8 3 13 8 19 8 24 3 23 16 16 21 9 16Z M12 12 14 13 M18 13 20 12 M13 17 19 17 M9 20 4 25 6 30 M23 20 28 25 26 30 M11 22 21 22 20 30 12 30Z',wolf:'M5 4 13 9 19 9 27 4 25 20 16 28 7 20Z M10 16 13 17 M19 17 22 16 M13 22 19 22 16 25Z',bat:'M16 13 13 9 12 14 3 8 6 22 11 18 16 25 21 18 26 22 29 8 20 14 19 9Z',swarm:'M14 12 18 12 20 18 18 24 14 24 12 18Z M13 15C1 2 1 21 13 19 M19 15C31 2 31 21 19 19 M14 8 12 5 M18 8 20 5 M13 18 19 18 M14 21 18 21',snake:'M5 25C25 30 29 18 18 16S3 4 16 4C25 4 27 10 22 12L18 10 M18 7 20 7 M23 11 28 13 30 11'}[id]}</path></svg>`;

export function mountCreatureEditor(characterPreview:ReturnType<typeof createPreview>|null){
  let category:CreatureCategory=new URLSearchParams(location.search).get('mode')==='creatures-sdf'?'sdf':'normal';
  let spec=presetCreature(category==='sdf'?'wolfSdf':'wolf'),tab='anatomy',active=false,preview:ReturnType<typeof createPreview>|null=null;
  let past:CreatureSpec[]=[],future:CreatureSpec[]=[],committed:CreatureSpec,saveTimer:number,frame=0,storageError='';
  try{spec=readCreatureDraft(localStorage,category);}catch{storageError='Rascunho indisponível. Exporte o JSON para guardar a criatura.';}
  committed=clone(spec);
  const drafts:Partial<Record<CreatureCategory,{spec:CreatureSpec;past:CreatureSpec[];future:CreatureSpec[];committed:CreatureSpec}>>={};
  const characterWorkspace=document.querySelector<HTMLElement>('.workspace')!,header=document.querySelector<HTMLElement>('.topbar')!;
  const nav=document.createElement('nav');nav.className='creator-modes';nav.setAttribute('aria-label','Tipo de criação');
  nav.innerHTML='<button id="mode-characters" aria-pressed="true">Personagens</button><button id="mode-creatures" aria-pressed="false">Criaturas <span>FLORESTA</span></button><button id="mode-creatures-sdf" aria-pressed="false">Criaturas SDF <span>FAUNA</span></button>';
  header.after(nav);
  const workspace=document.createElement('main');workspace.className='workspace creature-workspace';workspace.hidden=true;
  workspace.innerHTML=`<aside class="archive"><div class="section-eyebrow">BESTIÁRIO / FLORESTA</div><h1>A mata<br>também caça.</h1><p class="intro">Criaturas da floresta.<br>Crie a fauna do seu mundo.</p><div class="presets">${Object.entries(CREATURE_SPECIES).map(([id,label])=>`<button class="preset" data-species="${id}"><span class="creature-glyph">${{wolfLowpolySdf:'♜',wolfSdf:'♜',boar:'M3 17 7 10 20 10 26 15 30 15 30 21 25 22 22 27 M9 22 9 27 M7 10 9 5 14 10 M25 20 24 25 29 22',ratSdf:'M5 23C1 23 1 15 6 15 M6 22C6 10 20 10 25 18L29 20 24 23Z M17 13C12 3 23 3 22 15 M24 18 25 18 M10 23 9 27 M21 23 22 27',rat:'M5 23C1 23 1 15 6 15 M6 22C6 10 20 10 25 18L29 20 24 23Z M17 13C12 3 23 3 22 15 M24 18 25 18 M10 23 9 27 M21 23 22 27',skeleton:'☠',scorpion:'⋈',tarantulaSdf:'⋈',spider:'⋈',werewolfSdf:'♜',werewolf:'♜',wolf:'♜',bat:'⋈',swarm:'⁙',snake:'∿'}[id]}</span><span><strong>${label}</strong><small>${descriptions[id as CreatureSpecies]}</small>${getCreatureBuild(id as CreatureSpecies)?`<small class="creature-build-tag">${esc(getCreatureBuild(id as CreatureSpecies)!.name)}</small>`:''}</span></button>`).join('')}</div><div class="seed-card"><div class="section-eyebrow">GERAÇÃO PROCEDURAL</div><label for="creature-seed">Semente da criatura</label><div class="seed-row"><input id="creature-seed" maxlength="64" spellcheck="false"><button data-action="seed" title="Gerar com esta semente">${icon('arrow')}</button></div><button class="button randomize" data-action="random">${icon('dice')} Nova variação</button><p>A mesma espécie e semente recriam a mesma base.</p></div><div class="archive-footer"><span class="signal"></span> FAUNA PROCEDURAL<small>Receitas portáteis para Three.js</small></div></aside>
  <section class="stage-column" aria-label="Visualização da criatura"><div class="stage-heading"><div><span class="section-eyebrow">REGISTRO DE CRIATURA</span><h2 id="creature-title"></h2><p id="creature-subtitle"></p><span id="creature-build" class="creature-build-tag" hidden></span></div><div class="history-buttons"><button class="icon-button" data-action="undo" aria-label="Desfazer criatura">${icon('undo')}</button><button class="icon-button" data-action="redo" aria-label="Refazer criatura">${icon('redo')}</button></div></div><div class="viewport-wrap"><div class="view-controls">${[['iso','Isométrica'],['front','Frente'],['side','Lado'],['back','Costas']].map(([id,label])=>`<button data-creature-view="${id}" class="${id==='iso'?'active':''}">${label}</button>`).join('')}</div><div id="creature-viewport"></div><div class="viewport-tools"><button class="icon-button" data-action="rotate" aria-label="Girar criatura" aria-pressed="false">${icon('rotate')}</button><button class="icon-button" data-action="grid" aria-label="Grade da criatura" aria-pressed="true">${icon('grid')}</button><button class="icon-button" data-action="detail" aria-label="Alta definição da criatura" aria-pressed="true">HD</button><button class="icon-button" data-action="snapshot" aria-label="Salvar PNG da criatura">${icon('camera')}</button></div><div class="stage-coordinate"><span>FAUNA DA FLORESTA</span><span id="creature-render-mode">PRÉVIA 3D</span></div><div class="orbit-hint">ARRASTE PARA GIRAR · ROLE PARA APROXIMAR</div></div><div class="playback"><div class="playback-label"><span class="live-dot"></span> MOVIMENTO</div><div class="motion-buttons" id="creature-motions"></div><button class="icon-button" data-action="pause" aria-label="Pausar criatura" aria-pressed="false">${icon('pause',16)}</button></div><div class="stage-footer"><span id="creature-stats">Construindo criatura…</span><button class="text-button" data-action="sprites">Exportar 8 direções ${icon('download',13)}</button></div></section>
  <aside class="inspector"><div class="inspector-title"><span class="section-eyebrow">CONFIGURAÇÃO DA CRIATURA</span><span id="creature-save-state">Rascunho local</span></div><div class="tabs" role="tablist" aria-label="Configuração de criaturas">${[['anatomy','Corpo'],['appearance','Aparência'],['behavior','Ameaça']].map(([id,label])=>`<button id="creature-tab-${id}" role="tab" aria-controls="creature-panel" aria-selected="${id==='anatomy'}" data-creature-tab="${id}" class="${id==='anatomy'?'active':''}">${label}</button>`).join('')}</div><div id="creature-panel" role="tabpanel"></div><div class="inspector-bottom"><button class="button save-button" data-action="save">${icon('save')} Salvar rascunho da criatura</button><span>Separado dos personagens</span></div></aside><input id="creature-file" type="file" accept="application/json,.json" hidden>`;
  characterWorkspace.after(workspace);
  workspace.querySelectorAll<HTMLElement>('[data-species]').forEach(b=>{b.querySelector('.creature-glyph')!.innerHTML=speciesIcon(b.dataset.species!);});
  const $=<T extends HTMLElement=HTMLElement>(s:string)=>workspace.querySelector<T>(s)!;
  $('#creature-viewport').addEventListener('creature-generation-error',e=>notify((e as CustomEvent<string>).detail));
  const notify=(text:string)=>{const toast=document.querySelector<HTMLElement>('#toast')!;toast.textContent=text;toast.classList.add('visible');window.setTimeout(()=>toast.classList.remove('visible'),4000);};
  const read=(path:string)=>path.split('.').reduce((v:any,k)=>v[k],spec);
  const range=(path:string,label:string,min:number,max:number,step:number,unit='')=>{const v=read(path);return `<div class="field"><label for="c-${path}">${label}<output data-creature-output="${path}">${v}${unit}</output></label><input id="c-${path}" type="range" data-creature-path="${path}" data-unit="${unit}" min="${min}" max="${max}" step="${step}" value="${v}" style="--fill:${(v-min)/(max-min)*100}%"></div>`;};
  const color=(key:string,label:string)=>`<div class="field creature-color"><label for="c-${key}">${label}</label><input id="c-${key}" type="color" data-creature-path="appearance.${key}" value="${esc(read('appearance.'+key))}"></div>`;
  function panel(){
    const p=$('#creature-panel');p.setAttribute('aria-labelledby','creature-tab-'+tab);
    const heading=(title:string,description:string)=>`<div class="panel-heading"><div><h3>${title}</h3><p>${description}</p></div></div>`;
    if(tab==='anatomy')p.innerHTML=heading(CREATURE_SPECIES[spec.species],descriptions[spec.species])+`<div class="field"><label for="creature-name">Nome da criatura</label><input id="creature-name" maxlength="64" data-creature-path="name" value="${esc(spec.name)}"></div>`+range('body.scale','Escala geral',.5,1.8,.01,'×')+range('body.bulk','Volume corporal',0,1,.01)+CREATURE_FIELDS[spec.species].map(f=>range('anatomy.'+f.key,f.label,f.min,f.max,f.step)).join('');
    if(tab==='anatomy'&&['rat','ratSdf'].includes(spec.species))p.innerHTML+='<div class="section-eyebrow">FORMA DO RATO</div>'+Object.entries(ratControls).map(([key,label])=>range('rat.'+key,label,.7,1.3,.01)).join('');
    if(tab==='anatomy'&&spec.species==='spider')p.innerHTML+='<div class="section-eyebrow">FORMA DA ARANHA</div>'+Object.entries(spiderControls).map(([key,label])=>range('spider.'+key,label,.7,1.3,.01)).join('');
    if(tab==='anatomy'&&spec.species==='scorpion')p.innerHTML+='<div class="section-eyebrow">FORMA DO ESCORPIÃO</div>'+Object.entries(scorpionControls).map(([key,label])=>range('scorpion.'+key,label,.7,1.3,.01)).join('');
    if(tab==='appearance')p.innerHTML=heading('Cores e marcas','A identidade visual desta espécie.')+color('primary',{wolfLowpolySdf:'Pelagem principal',wolfSdf:'Pelagem principal',boar:'Pelagem principal',ratSdf:'Pelagem principal',rat:'Pelagem principal',skeleton:'Ossos principais',scorpion:'Carapaça principal',tarantulaSdf:'Carapaça e pelagem',spider:'Carapaça principal',werewolfSdf:'Pelagem principal',werewolf:'Pelagem principal',wolf:'Pelagem principal',bat:'Corpo e dedos das asas',swarm:'Cor dos insetos',snake:'Escamas'}[spec.species])+color('secondary',{wolfLowpolySdf:'Ventre e contraste da pelagem',wolfSdf:'Ventre e contraste da pelagem',boar:'Ventre e contraste da pelagem',ratSdf:'Ventre e contraste da pelagem',rat:'Ventre, focinho e patas',skeleton:'Interior e partes posteriores',scorpion:'Articulações das patas e cauda',tarantulaSdf:'Contraste dos pelos',spider:'Articulações das patas',werewolfSdf:'Peito, focinho e patas',werewolf:'Peito, focinho e patas',wolf:'Focinho e ventre',bat:'Membrana e peito',swarm:'Asas e faixas',snake:'Ventre e padrão'}[spec.species])+(spec.species!=='swarm'?color('eyes',spec.species==='skeleton'?'Cavidades do crânio':'Cor dos olhos'):'')+(spec.species==='skeleton'?'':range('appearance.markings','Contraste das marcas',0,1,.01));
    if(tab==='behavior')p.innerHTML=heading('Ameaça da floresta','Ficha inicial para integrar ao seu jogo.')+`<div class="field"><label for="creature-temperament">Temperamento</label><select id="creature-temperament" data-creature-path="behavior.temperament">${Object.entries({defensive:'Defensivo',territorial:'Territorial',aggressive:'Agressivo'}).map(([id,label])=>`<option value="${id}" ${spec.behavior.temperament===id?'selected':''}>${label}</option>`).join('')}</select></div>`+range('behavior.health','Vida',1,500,1)+range('behavior.damage','Dano por ataque',0,100,1)+range('behavior.speed','Velocidade de deslocamento',.1,12,.1,' m/s')+range('behavior.detection','Raio de percepção',1,40,1,' m')+(['snake','swarm','spider','tarantulaSdf','scorpion'].includes(spec.species)?`<label class="toggle-row"><span><strong>Venenoso</strong><small>Habilitar veneno na ficha</small></span><input type="checkbox" data-creature-path="behavior.venomous" ${spec.behavior.venomous?'checked':''}><span class="toggle"></span></label>`:'')+'<div class="panel-note">Estes valores são exportados no JSON. Dano, veneno, percepção e inteligência artificial precisam ser aplicados pelo jogo. '+(['werewolfSdf','wolfLowpolySdf','wolfSdf','boar','scorpion','spider','tarantulaSdf','skeleton','rat','ratSdf'].includes(spec.species)?'O ataque é um golpe único; clique no botão de ataque para repetir.':'A animação abaixo é uma prévia em loop.')+'</div>';
  }
  function summary(){
    const sdf=category==='sdf';
    $('.archive .section-eyebrow').textContent=sdf?'BESTIÁRIO / FAUNA SDF':'BESTIÁRIO / FLORESTA';
    $('.archive h1').innerHTML=sdf?'Fauna<br>Procedural SDF.':'A mata<br>também caça.';
    $('.archive .intro').textContent=sdf?'Criaturas da base Fauna Procedural — SDF.':'Criaturas da floresta. Crie a fauna do seu mundo.';
    $('.stage-coordinate span').textContent=sdf?'FAUNA PROCEDURAL — SDF':'FAUNA DA FLORESTA';
    const build=getCreatureBuild(spec.species),badge=$('#creature-build');
    badge.hidden=!build;badge.textContent=build?`${build.name} · v${build.integrationVersion}`:'';
    badge.title=build?`${build.source} ${build.sourceVersion} · MIT · ${build.sourceCommit}`:'';
    $('#creature-title').textContent=spec.name;$('#creature-subtitle').textContent=CREATURE_SPECIES[spec.species]+' / '+spec.body.scale.toFixed(2)+'× / '+spec.behavior.temperament.replace('territorial','territorial').replace('defensive','defensivo').replace('aggressive','agressivo');
    $('[data-action="undo"]').toggleAttribute('disabled',!past.length);$('[data-action="redo"]').toggleAttribute('disabled',!future.length);
    workspace.querySelectorAll<HTMLElement>('[data-species]').forEach(b=>{b.hidden=creatureCategory(b.dataset.species as CreatureSpecies)!==category;const selected=b.dataset.species===spec.species;b.classList.toggle('selected',selected);b.setAttribute('aria-pressed',String(selected));});
  }
  function persist(){clearTimeout(saveTimer);try{localStorage.setItem(creatureDraftKey(category),JSON.stringify(validateCreatureSpec(spec)));$('#creature-save-state').textContent='Rascunho salvo';}catch{$('#creature-save-state').textContent='Exporte para salvar';}}
  let generation=0;
  async function rebuildPreview(){const id=++generation,current=clone(spec);try{if(!!getCreatureBuild(current.species)){$('#creature-stats').textContent=`Gerando ${CREATURE_SPECIES[current.species]} em segundo plano…`;await prepareFauna(current,preview?.detailLevel==='low'?'low':'high');}if(id===generation&&preview)preview.setCreature(current);}catch(e){if(id===generation){$('#creature-stats').textContent='Falha na geração — tente novamente';notify((e as Error).message);}}}
  function refresh(rebuild=true){summary();if(rebuild&&preview){cancelAnimationFrame(frame);generation++;frame=requestAnimationFrame(()=>{void rebuildPreview();});}clearTimeout(saveTimer);$('#creature-save-state').textContent='Alterações…';saveTimer=window.setTimeout(persist,450);}
  function commit(){if(JSON.stringify(spec)!==JSON.stringify(committed)){past.push(clone(committed));past=past.slice(-30);future=[];committed=clone(spec);}summary();}
  function renderMotions(){const keys:CreatureMotion[]=['idle','move',...(['werewolfSdf','wolfLowpolySdf','wolfSdf','boar','wolf','werewolf','spider','tarantulaSdf','scorpion','skeleton','rat','ratSdf'].includes(spec.species)?['run' as const]:[]),...(spec.species==='skeleton'?['sprint' as const]:[]),...(['rat','ratSdf'].includes(spec.species)?['runPlus' as const]:[]),'attack'];const labels={idle:motions[spec.species][0],move:motions[spec.species][1],run:'Correr',sprint:'Correr+',runPlus:'Correr+',attack:motions[spec.species][2]};$('#creature-motions').innerHTML=keys.map(key=>`<button data-creature-motion="${key}" class="${(preview?.motion??'idle')===key?'active':''}">${labels[key]}</button>`).join('');}
  function switchCreatureCategory(next:CreatureCategory){
    if(next===category)return;
    persist();drafts[category]={spec:clone(spec),past,future,committed:clone(committed)};
    category=next;const draft=drafts[next];
    if(draft){spec=clone(draft.spec);past=draft.past;future=draft.future;committed=clone(draft.committed);}
    else{try{spec=readCreatureDraft(localStorage,next);}catch{spec=presetCreature(next==='sdf'?'wolfSdf':'wolf');}past=[];future=[];committed=clone(spec);}
    panel();$<HTMLInputElement>('#creature-seed').value=spec.seed;preview?.setMotion('idle');renderMotions();refresh();
  }
  function replace(next:CreatureSpec){const valid=validateCreatureSpec(next);if(creatureCategory(valid.species)!==category)setMode(true,creatureCategory(valid.species));spec=valid;commit();panel();$('#creature-seed').setAttribute('value',spec.seed);($<HTMLInputElement>('#creature-seed')).value=spec.seed;preview?.setMotion('idle');renderMotions();refresh();}
  function filename(){return spec.name.normalize('NFD').replace(/[\u0300-\u036f]/g,'').replace(/[^a-z0-9_-]+/gi,'-').toLowerCase()||'criatura';}
  function download(url:string,name:string){const a=document.createElement('a');a.href=url;a.download=name;document.body.append(a);a.click();a.remove();}
  function exportRecipe(){try{const url=URL.createObjectURL(new Blob([JSON.stringify(validateCreatureSpec(spec),null,2)],{type:'application/json'}));download(url,filename()+'.criatura.json');setTimeout(()=>URL.revokeObjectURL(url),1000);notify('Receita da criatura exportada.');}catch(e){notify((e as Error).message);}}
  function setMode(creatures:boolean,next:CreatureCategory=category){
    if(creatures)switchCreatureCategory(next);
    if(creatures){const url=new URL(location.href);url.searchParams.set('mode',category==='sdf'?'creatures-sdf':'creatures');window.history.replaceState(null,'',url);}
    active=creatures;characterWorkspace.hidden=creatures;workspace.hidden=!creatures;characterPreview?.setActive(!creatures);preview?.setActive(creatures);
    const villains=characterWorkspace.dataset.characterCategory==='villains';
    nav.querySelector('#mode-characters')!.setAttribute('aria-pressed',String(!creatures&&!villains));nav.querySelector('#mode-villains')?.setAttribute('aria-pressed',String(!creatures&&villains));nav.querySelector('#mode-creatures')!.setAttribute('aria-pressed',String(creatures));
    nav.querySelector('#mode-creatures')!.setAttribute('aria-pressed',String(creatures&&category==='normal'));nav.querySelector('#mode-creatures-sdf')!.setAttribute('aria-pressed',String(creatures&&category==='sdf'));
    header.querySelector('.brand small')!.textContent=creatures?'CRIATURAS':villains?'PERSONAGEM ZUMBI':'PERSONAGENS';header.querySelector('#export span')!.textContent=creatures?'Exportar criatura':'Exportar personagem';
    if(creatures&&category==='sdf')header.querySelector('.brand small')!.textContent='CRIATURAS SDF';
    header.querySelector('.project-status')!.innerHTML='<i></i> '+(creatures?'BESTIÁRIO DA FLORESTA':villains?'OFICINA DE ZUMBIS':'OFICINA DE SOBREVIVENTES')+' <span class="version">V1.1</span>';
    if(creatures&&category==='sdf')header.querySelector('.project-status')!.innerHTML='<i></i> BESTIÁRIO SDF <span class="version">V1.1</span>';
    if(creatures&&!preview){try{preview=createPreview($('#creature-viewport'),s=>$('#creature-stats').textContent=Math.round(s.triangles).toLocaleString('pt-BR')+(getCreatureBuild(spec.species)?' triângulos base':' triângulos')+' · '+s.meshes+' peças');void rebuildPreview();preview.view('iso');if(preview.compatible)$('#creature-render-mode').textContent='MODO COMPATÍVEL';}catch(e){$('#creature-stats').textContent='Prévia indisponível';notify((e as Error).message);}}
    if(creatures&&storageError){notify(storageError);storageError='';}
  }
  nav.querySelector('#mode-characters')!.addEventListener('click',()=>setMode(false));nav.querySelector('#mode-creatures')!.addEventListener('click',()=>setMode(true,'normal'));nav.querySelector('#mode-creatures-sdf')!.addEventListener('click',()=>setMode(true,'sdf'));
  // Capture header actions only while the creature workspace is selected.
  for(const id of ['import','export'])header.querySelector('#'+id)!.addEventListener('click',e=>{if(!active)return;e.stopImmediatePropagation();if(id==='export')exportRecipe();else $<HTMLInputElement>('#creature-file').click();},true);
  $('#creature-file').addEventListener('change',async()=>{const input=$<HTMLInputElement>('#creature-file'),file=input.files?.[0];if(!file)return;try{if(file.size>100000)throw new Error('O JSON deve ter até 100 KB.');replace(validateCreatureSpec(JSON.parse(await file.text())));notify('Criatura importada.');}catch(e){notify((e as Error).message);}finally{input.value='';}});
  workspace.addEventListener('input',e=>{
    const el=e.target as HTMLInputElement,path=el.dataset.creaturePath;if(!path)return;
    const next=clone(spec),keys=path.split('.'),last=keys.pop()!,obj=keys.reduce((v:any,k)=>v[k],next);
    obj[last]=el.type==='checkbox'?el.checked:el.type==='range'?Number(el.value):el.value;
    if(['rat','ratSdf'].includes(next.species)&&next.rat){const sync={'anatomy.length':'bodyLength','anatomy.spread':'bodyWidth','anatomy.legs':'legLength','anatomy.ears':'earSize','anatomy.tail':'tailLength','anatomy.thickness':'tailThickness'} as const;const key=sync[path as keyof typeof sync];if(key)next.rat[key]=Number(el.value);}
    if(next.species==='spider'&&next.spider){const sync:Record<string,'legLength'|'legSpread'|'legThickness'>={'anatomy.legs':'legLength','anatomy.spread':'legSpread','anatomy.thickness':'legThickness'};if(sync[path])next.spider[sync[path]]=Number(el.value);}
    if(path==='name'&&!el.value.trim())obj[last]='Criatura sem nome';
    if(next.species==='scorpion'&&next.scorpion){const sync:Record<string,'legLength'|'legSpread'|'legThickness'|'tailLength'>={'anatomy.legs':'legLength','anatomy.spread':'legSpread','anatomy.thickness':'legThickness','anatomy.tail':'tailLength'};if(sync[path])next.scorpion[sync[path]]=Number(el.value);}
    try{spec=validateCreatureSpec(next);}catch(e){notify((e as Error).message);return;}
    const output=workspace.querySelector(`[data-creature-output="${path}"]`);if(output)output.textContent=el.value+(el.dataset.unit??'');
    if(el.type==='range')el.style.setProperty('--fill',(Number(el.value)-Number(el.min))/(Number(el.max)-Number(el.min))*100+'%');
    refresh(path!=='name'&&!path.startsWith('behavior.'));
  });
  workspace.addEventListener('change',e=>{if((e.target as HTMLElement).dataset.creaturePath)commit();});
  $('#creature-seed').addEventListener('keydown',e=>{if(e.key==='Enter')$('[data-action="seed"]').click();});
  workspace.addEventListener('click',async e=>{
    const b=(e.target as HTMLElement).closest<HTMLElement>('button');if(!b)return;
    try{
      if(b.dataset.species){replace(presetCreature(b.dataset.species as CreatureSpecies));return;}
      if(b.dataset.creatureTab){tab=b.dataset.creatureTab;workspace.querySelectorAll<HTMLElement>('[data-creature-tab]').forEach(q=>{q.classList.toggle('active',q===b);q.setAttribute('aria-selected',String(q===b));});panel();return;}
      if(b.dataset.creatureView){preview?.view(b.dataset.creatureView);workspace.querySelectorAll('[data-creature-view]').forEach(q=>q.classList.toggle('active',q===b));return;}
      if(b.dataset.creatureMotion){preview?.setMotion(b.dataset.creatureMotion as CreatureMotion);renderMotions();return;}
      const action=b.dataset.action;
      if(action==='random'||action==='seed'){const seed=action==='seed'?$<HTMLInputElement>('#creature-seed').value.trim():String(crypto.getRandomValues(new Uint32Array(1))[0]);if(!seed)throw new Error('Digite uma semente.');replace(randomCreature(seed,spec.species));}
      if(action==='save'){persist();notify($('#creature-save-state').textContent==='Rascunho salvo'?'Rascunho da criatura salvo.':'Armazenamento indisponível. Exporte o JSON.');}
      if(action==='undo'||action==='redo'){const from=action==='undo'?past:future,to=action==='undo'?future:past;if(from.length){to.push(clone(spec));spec=from.pop()!;committed=clone(spec);panel();$<HTMLInputElement>('#creature-seed').value=spec.seed;renderMotions();refresh();}}
      if(action==='snapshot'||action==='sprites'){if(!preview)throw new Error('Prévia indisponível.');b.setAttribute('disabled','');try{download(await (action==='snapshot'?preview.snapshot():preview.spriteSheet()),filename()+(action==='snapshot'?'.png':'.8-direcoes.png'));}finally{b.removeAttribute('disabled');}}
      if(preview&&['rotate','grid','detail','pause'].includes(action??'')){const on=preview[action as 'rotate'|'grid'|'detail'|'pause']();b.setAttribute('aria-pressed',String(on));if(action==='pause'){b.innerHTML=icon(on?'play':'pause',16);b.setAttribute('aria-label',on?'Retomar criatura':'Pausar criatura');}}
    }catch(e){notify((e as Error).message);}
  });
  panel();summary();renderMotions();$<HTMLInputElement>('#creature-seed').value=spec.seed;
  (window as any).__ABRIGO_CREATURES__={getSpec:()=>clone(spec),setSpec:(s:unknown)=>replace(validateCreatureSpec(s)),getPreview:()=>preview,setMode};
  if(['creatures','creatures-sdf'].includes(new URLSearchParams(location.search).get('mode')??''))setMode(true);
}
