import {PERFORMANCE_PROFILES,validateGamePerformance,type GamePerformance} from './game-performance';
export function mountPerformanceControls(host:HTMLElement,read:()=>GamePerformance,change:(value:GamePerformance)=>void,save:()=>void){
 const panel=document.createElement('details');panel.className='game-performance-controls';
 panel.innerHTML=`<summary>Desempenho</summary><div class="game-device-settings"><label>Perfil<select data-performance="profile"><option value="custom">Personalizado</option>${Object.entries(PERFORMANCE_PROFILES).map(([key,p])=>`<option value="${key}">${p.label}</option>`).join('')}</select></label><label>Resolução (limite de pixels)<select data-performance="resolution">${[.5,.75,1,1.5,2].map(n=>`<option value="${n}">${n}×</option>`).join('')}</select></label><label>Sombras<select data-performance="shadows">${[0,512,1024,2048,4096].map(n=>`<option value="${n}">${n?n+' px':'OFF'}</option>`).join('')}</select></label><label>Limite de FPS<select data-performance="fps"><option value="30">30</option><option value="60">60</option><option value="0">Sem limite</option></select></label><label><input type="checkbox" data-performance="post"> Pós-processamento</label><label><input type="checkbox" data-performance="reflections"> Reflexos dinâmicos da água</label></div><p class="game-help">Compare os perfis no mesmo local. Não altera o mapa, as colisões ou a quantidade de vegetação. O Equilibrado inicia sem pós-processamento e reflexos dinâmicos.</p><button class="button" data-performance-save>Salvar desempenho</button><p data-performance-status role="status"></p>`;
 host.append(panel);
 const sync=()=>{const value=read();panel.querySelectorAll<HTMLInputElement|HTMLSelectElement>('[data-performance]').forEach(el=>{const key=el.dataset.performance!;if(key==='profile'){el.value=Object.entries(PERFORMANCE_PROFILES).find(([,p])=>JSON.stringify(p.settings)===JSON.stringify(value))?.[0]??'custom';}else if(el instanceof HTMLInputElement)el.checked=value[key as 'post'|'reflections'];else el.value=String(value[key as keyof GamePerformance]);});};
 panel.addEventListener('change',e=>{const el=e.target as HTMLInputElement,key=el.dataset.performance;if(!key)return;if(key==='profile'){if(PERFORMANCE_PROFILES[el.value])change({...PERFORMANCE_PROFILES[el.value].settings});}else change(validateGamePerformance({...read(),[key]:el.type==='checkbox'?el.checked:Number(el.value)}));sync();});
 panel.querySelector('[data-performance-save]')!.addEventListener('click',()=>{const status=panel.querySelector('[data-performance-status]')!;try{save();status.textContent='Desempenho salvo neste navegador.';}catch{status.textContent='Não foi possível salvar. A configuração continua ativa neste teste.';}});
 sync();return {panel,sync};
}
